FROM ubuntu:12.04

#
# Install postgresql
#
RUN apt-get update && apt-get install -y iputils-ping postgresql-9.1 nano net-tools

#
# Setup configuration
#
RUN /bin/echo -e "                                               \
        host    all             all     0.0.0.0/0   md5      \n  \
        host    replication     all     0.0.0.0/0   trust    \n  \
    " >> /etc/postgresql/9.1/main/pg_hba.conf                    \
    && /bin/echo -e "                                            \
        listen_addresses = '*'                               \n  \
        port=5432                                            \n  \
        hot_standby = on                                     \n  \
    " >> /etc/postgresql/9.1/main/postgresql.conf                

#
# Add startup script. This will perform initial replication and start
# the server. This must be run with the master server running and linked
# at pg_master
#
#
RUN chmod -R 777 /tmp
COPY recovery.conf /var/lib/postgresql/9.1/main/recovery.conf
COPY run.sh /var/lib/postgresql/9.1/run.sh

USER postgres
EXPOSE 5432
CMD /var/lib/postgresql/9.1/run.sh
