master:
  build: ./
  dockerfile: Dockerfile-master
  ports:
        - "5432:5432"
  volumes:
   - ./src:/tmp/

slave:
  build: ./
  dockerfile: Dockerfile-slave
  ports:
        - "5431:5432"
  volumes:
   - ./src:/tmp/

  links: 
   - master
